import { createHash } from 'node:crypto'
import { mkdtemp, mkdir, open, readFile, rename, rm, stat, symlink, utimes, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { Readable } from 'node:stream'
import type { IncomingMessage, ServerResponse } from 'node:http'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { appendGallery, readGalleryImageHash } from '../src/gallery-store.ts'
import { appendHistory, readHistoryImageHash } from '../src/history-store.ts'
import { setImageDataRoot } from '../src/image-storage-path.ts'
import { GALLERY_API, HISTORY_API, type HistoryEntry, type HistoryEntryInput } from '../src/protocol.ts'
import { makeRoutes, type ImageGenRoutesDeps } from '../src/routes.ts'
import { readStoredImageHash } from '../src/stored-image-hash.ts'

vi.mock('node:fs/promises', async importOriginal => {
  const original = await importOriginal<typeof import('node:fs/promises')>()
  return { ...original, open: vi.fn(original.open) }
})

let root = ''
beforeEach(async () => {
  root = await mkdtemp(path.join(tmpdir(), 'imagegen-byte-hash-'))
  setImageDataRoot(root)
  vi.mocked(open).mockClear()
})
afterEach(async () => {
  setImageDataRoot(undefined)
  await rm(root, { recursive: true, force: true })
})

function sha256(bytes: string | Buffer): string { return createHash('sha256').update(bytes).digest('hex') }
function entryInput(id: string, bytes: string): HistoryEntryInput {
  return { id, createdAt: Date.now(), mode: 'text', model: 'image', prompt: id, size: '1:1', quality: 'auto', detail: '', n: 1, images: [{ b64: Buffer.from(bytes).toString('base64'), mime: 'image/png' }] }
}
function entry(id: string, base = HISTORY_API.image, extra: Partial<HistoryEntry> = {}): HistoryEntry {
  return { ...entryInput(id, ''), images: [{ url: `${base}/${id}-0.png`, mime: 'image/png' }], ...extra }
}
const basicDeps: ImageGenRoutesDeps = { settings: { describe: () => [], mutate: async () => {} }, resolve: () => ({ apiUrl: '', apiKey: '' }) }

async function call(pathname: string, body: unknown = {}, dependencies: ImageGenRoutesDeps = basicDeps): Promise<{ status: number; body: any }> {
  const req = Object.assign(Readable.from(body === undefined ? [] : [Buffer.from(JSON.stringify(body))]), {
    method: 'POST', url: pathname, socket: { remoteAddress: '127.0.0.1' }, headers: { host: 'localhost:8888' },
  }) as unknown as IncomingMessage
  let status = 0
  let payload = ''
  const res = { writeHead: (code: number) => { status = code }, end: (data: string | Buffer) => { payload = data.toString() } } as unknown as ServerResponse
  await makeRoutes(dependencies).find(route => route.path === pathname)!.handler(req, res)
  return { status, body: JSON.parse(payload) }
}

describe('stored image byte hashes', () => {
  it('hashes raw bytes consistently across history and gallery without changing indexes', async () => {
    const bytes = 'same generated bytes'
    await appendHistory(entryInput('history', bytes))
    await appendGallery(entryInput('gallery', bytes))
    const before = await Promise.all([readFile(path.join(root, 'index.json')), readFile(path.join(root, 'gallery/index.json'))])
    expect(await readHistoryImageHash('history-0.png')).toBe(sha256(bytes))
    expect(await readGalleryImageHash('gallery-0.png')).toBe(sha256(bytes))
    expect(await Promise.all([readFile(path.join(root, 'index.json')), readFile(path.join(root, 'gallery/index.json'))])).toEqual(before)
  })

  it('reuses unchanged bytes, then invalidates same-size edits even when mtime is restored', async () => {
    await mkdir(path.join(root, 'images'))
    const filePath = path.join(root, 'images/image-0.png')
    await writeFile(filePath, 'first')
    const oldStat = await stat(filePath)
    expect(await readHistoryImageHash('image-0.png')).toBe(sha256('first'))
    expect(await readHistoryImageHash('image-0.png')).toBe(sha256('first'))
    expect(open).toHaveBeenCalledTimes(1)
    await writeFile(filePath, 'other')
    await utimes(filePath, oldStat.atime, oldStat.mtime)
    expect(await readHistoryImageHash('image-0.png')).toBe(sha256('other'))
    expect(open).toHaveBeenCalledTimes(2)
  })

  it('invalidates file replacement and removal and isolates a changed data root', async () => {
    await mkdir(path.join(root, 'images'))
    const filePath = path.join(root, 'images/image-0.png')
    await writeFile(filePath, 'first')
    expect(await readHistoryImageHash('image-0.png')).toBe(sha256('first'))
    const oldStat = await stat(filePath)
    await writeFile(path.join(root, 'replacement'), 'other')
    await utimes(path.join(root, 'replacement'), oldStat.atime, oldStat.mtime)
    await rename(path.join(root, 'replacement'), filePath)
    expect(await readHistoryImageHash('image-0.png')).toBe(sha256('other'))
    const otherRoot = path.join(root, 'other')
    await mkdir(path.join(otherRoot, 'images'), { recursive: true })
    await writeFile(path.join(otherRoot, 'images/image-0.png'), 'different root')
    setImageDataRoot(otherRoot)
    expect(await readHistoryImageHash('image-0.png')).toBe(sha256('different root'))
    setImageDataRoot(root)
    await rm(filePath)
    expect(await readHistoryImageHash('image-0.png')).toBeUndefined()
    await writeFile(filePath, 'after removal')
    expect(await readHistoryImageHash('image-0.png')).toBe(sha256('after removal'))
  })

  it('does not follow symlinks, accept traversal or create a missing store', async () => {
    await mkdir(path.join(root, 'images'))
    await writeFile(path.join(root, 'secret'), 'never read')
    await symlink(path.join(root, 'secret'), path.join(root, 'images/link-0.png'))
    await mkdir(path.join(root, 'images/directory-0.png'))
    for (const name of ['../secret', '/secret', 'nested/image-0.png', 'image-0.png?query', 'image-0.svg', 'link-0.png', 'directory-0.png', 'missing-0.png']) {
      expect(await readHistoryImageHash(name)).toBeUndefined()
    }
    expect(open).not.toHaveBeenCalled()
    const missingRoot = path.join(root, 'absent')
    expect(await readStoredImageHash(path.join(missingRoot, 'images'), 'image-0.png')).toBeUndefined()
    await expect(stat(missingRoot)).rejects.toMatchObject({ code: 'ENOENT' })
  })

  it('bounds cached file versions instead of retaining every old image', async () => {
    await mkdir(path.join(root, 'images'))
    for (let index = 0; index <= 512; index++) {
      const file = `cache-${index}-0.png`
      await writeFile(path.join(root, 'images', file), `bytes ${index}`)
      expect(await readHistoryImageHash(file)).toBe(sha256(`bytes ${index}`))
    }
    vi.mocked(open).mockClear()
    expect(await readHistoryImageHash('cache-512-0.png')).toBe(sha256('bytes 512'))
    expect(open).not.toHaveBeenCalled()
    expect(await readHistoryImageHash('cache-0-0.png')).toBe(sha256('bytes 0'))
    expect(open).toHaveBeenCalledOnce()
  })

  it('streams at most three images even across simultaneous store hash requests', async () => {
    await mkdir(path.join(root, 'images'))
    const files = Array.from({ length: 8 }, (_, index) => `stream-${index}-0.png`)
    await Promise.all(files.map(file => writeFile(path.join(root, 'images', file), Buffer.alloc(128 * 1024, file))))
    const original = await vi.importActual<typeof import('node:fs/promises')>('node:fs/promises')
    let active = 0
    let maximum = 0
    vi.mocked(open).mockImplementation(async (...args) => {
      const handle = await original.open(...args)
      return {
        stat: handle.stat.bind(handle), close: handle.close.bind(handle),
        createReadStream: () => (async function* () {
          active++
          maximum = Math.max(maximum, active)
          try {
            await new Promise<void>(resolve => setImmediate(resolve))
            for await (const chunk of handle.createReadStream({ autoClose: false })) yield chunk
          } finally { active-- }
        })(),
      } as unknown as Awaited<ReturnType<typeof open>>
    })
    try {
      const hashes = await Promise.all(files.map(file => readHistoryImageHash(file)))
      expect(hashes).toEqual(files.map(file => sha256(Buffer.alloc(128 * 1024, file))))
      expect(maximum).toBe(3)
      expect(active).toBe(0)
    } finally { vi.mocked(open).mockImplementation(original.open) }
  })
})

describe('opt-in history and gallery list hashes', () => {
  it('leaves ordinary lists lightweight and includes equal hashes only when requested', async () => {
    await appendHistory(entryInput('history', 'same bytes'))
    await appendGallery(entryInput('gallery', 'same bytes'))
    const before = await readFile(path.join(root, 'index.json'))
    expect((await call(HISTORY_API.list)).body.entries[0].images[0].sha256).toBeUndefined()
    expect((await call(GALLERY_API.list)).body.entries[0].images[0].sha256).toBeUndefined()
    expect(open).not.toHaveBeenCalled()
    const history = (await call(HISTORY_API.list, { includeImageHashes: true })).body
    const gallery = (await call(GALLERY_API.list, { includeImageHashes: true })).body
    expect(history.entries[0].images[0].sha256).toBe(sha256('same bytes'))
    expect(gallery.entries[0].images[0].sha256).toBe(history.entries[0].images[0].sha256)
    expect(await readFile(path.join(root, 'index.json'))).toEqual(before)
    expect((await call(HISTORY_API.list)).body.entries[0].images[0].sha256).toBeUndefined()
  })

  it('only hashes the requested history scope and tolerates a deleted image', async () => {
    await appendHistory(entryInput('normal', 'normal bytes'))
    await appendHistory({ ...entryInput('canvas', 'canvas bytes'), canvas: { canvasId: 'canvas' } })
    await appendHistory(entryInput('missing', 'missing bytes'))
    await rm(path.join(root, 'images/missing-0.png'))
    const result = (await call(HISTORY_API.list, { scope: 'normal', includeImageHashes: true })).body
    expect(result.ok).toBe(true)
    expect(result.entries.map((item: HistoryEntry) => item.id)).toEqual(['missing', 'normal'])
    expect(result.entries[0].images[0].sha256).toBeUndefined()
    expect(result.entries[1].images[0].sha256).toBe(sha256('normal bytes'))
    expect(open).toHaveBeenCalledTimes(1)
  })

  it('rejects a malformed opt-in flag without reading any image', async () => {
    for (const pathname of [HISTORY_API.list, GALLERY_API.list]) {
      expect((await call(pathname, { includeImageHashes: 'true' })).body.code).toBe('bad-request')
      expect((await call(pathname, { includeImageHashes: null })).body.code).toBe('bad-request')
      expect((await call(pathname, { includeImageHashes: false })).body.ok).toBe(true)
    }
    expect(open).not.toHaveBeenCalled()
  })

  it('supports legacy injected byte stores and never trusts existing metadata hashes', async () => {
    const original = entry('legacy', HISTORY_API.image, { images: [{ url: `${HISTORY_API.image}/legacy-0.png`, mime: 'image/png', sha256: 'f'.repeat(64) }] })
    const readImage = vi.fn(async () => ({ data: Buffer.from('actual bytes'), mime: 'image/png' }))
    const dependencies: ImageGenRoutesDeps = { ...basicDeps, history: { list: async () => [original], append: async () => [], clear: async () => [], remove: async () => [], readImage } }
    expect((await call(HISTORY_API.list, {}, dependencies)).body.entries).toEqual([original])
    expect(readImage).not.toHaveBeenCalled()
    const result = (await call(HISTORY_API.list, { includeImageHashes: true }, dependencies)).body
    expect(readImage).toHaveBeenCalledExactlyOnceWith('legacy-0.png')
    expect(result.entries[0].images[0].sha256).toBe(sha256('actual bytes'))
    expect(original.images[0].sha256).toBe('f'.repeat(64))
  })

  it('does not send arbitrary relative, absolute, encoded or foreign store URLs to a backend', async () => {
    const urls = [
      `${HISTORY_API.image}/../secret`, `${HISTORY_API.image}/nested/image-0.png`,
      `${HISTORY_API.image}/image-0.png?x=1`, `${HISTORY_API.image}/image-0.png#x`,
      `${HISTORY_API.image}/%2e%2e%2fsecret-0.png`, `https://localhost${HISTORY_API.image}/image-0.png`,
      `${GALLERY_API.image}/image-0.png`, '//other-host/image-0.png',
    ]
    const images = urls.map(url => ({ url, mime: 'image/png', sha256: 'f'.repeat(64) }))
    const readImage = vi.fn(async () => undefined)
    const dependencies: ImageGenRoutesDeps = { ...basicDeps, history: { list: async () => [entry('invalid', HISTORY_API.image, { images })], append: async () => [], clear: async () => [], remove: async () => [], readImage } }
    const result = (await call(HISTORY_API.list, { includeImageHashes: true }, dependencies)).body
    expect(result.ok).toBe(true)
    expect(result.entries[0].images.every((image: { sha256?: string }) => image.sha256 === undefined)).toBe(true)
    expect(readImage).not.toHaveBeenCalled()
  })

  it('limits list hash reads to three and retains other metadata when one read fails', async () => {
    let active = 0
    let maximum = 0
    const readImageHash = vi.fn(async (file: string) => {
      active++
      maximum = Math.max(maximum, active)
      await new Promise<void>(resolve => setImmediate(resolve))
      active--
      if (file === 'broken-0.png') throw new Error('unreadable file')
      return sha256(file)
    })
    const entries = [entry('broken'), ...Array.from({ length: 10 }, (_, index) => entry(`image-${index}`))]
    const readImage = vi.fn(async () => undefined)
    const dependencies: ImageGenRoutesDeps = { ...basicDeps, history: { list: async () => entries, append: async () => [], clear: async () => [], remove: async () => [], readImage, readImageHash } }
    const result = (await call(HISTORY_API.list, { includeImageHashes: true }, dependencies)).body
    expect(result.ok).toBe(true)
    expect(maximum).toBe(3)
    expect(result.entries.map((item: HistoryEntry) => item.id)).toEqual(entries.map(item => item.id))
    expect(result.entries[0].images[0].sha256).toBeUndefined()
    expect(result.entries[1].images[0].sha256).toBe(sha256('image-0-0.png'))
    expect(readImage).not.toHaveBeenCalled()
  })
})
