import { activeImageGenLanguage } from './helpers.ts'

const en = {
  trigger: 'Task history',
  title: 'Ecommerce task history',
  activeCount: '{count} active tasks',
  search: 'Search product names or prompts',
  statusFilter: 'Task status',
  modelFilter: 'Model',
  sizeFilter: 'Aspect ratio',
  allStatuses: 'All statuses',
  allModels: 'All models',
  allSizes: 'All ratios',
  autoSize: 'Auto',
  loading: 'Loading task history…',
  empty: 'No ecommerce tasks yet. Generate a product image set to save a task here.',
  noMatches: 'No tasks match these filters.',
  resetFilters: 'Reset filters',
  retry: 'Retry',
  refresh: 'Refresh',
  close: 'Close task history',
  clear: 'Clear finished ecommerce tasks…',
  clearHint: 'Active tasks are kept. Only ecommerce tasks are cleared.',
  open: 'Open {name}',
  opening: 'Opening…',
  actions: 'Actions for {name}',
  remove: 'Delete task…',
  cancel: 'Cancel task…',
  operationError: 'Action failed: {message}',
  progress: '{done}/{total} complete',
  legacyProgress: '{count} saved results',
  untitled: 'Unnamed product',
  legacy: 'Older task',
  legacyWarning: 'This older task saved only its results. Its original configuration and reference images cannot be restored.',
  viewing: 'Viewing a saved task',
  copyConfig: 'Copy configuration to a new task',
  returnDraft: 'Return to draft',
  modelUnavailable: 'The saved model or provider is unavailable. Copy the configuration and choose an available model to generate again.',
  deleteConfirm: 'Delete “{name}” and its saved results? This cannot be undone.',
  clearConfirm: 'Delete {count} finished ecommerce tasks and their saved results? {active} active tasks will be kept. Normal image history, canvas records and gallery items are unaffected.',
  cancelConfirm: 'Cancel “{name}”? Images already completed will be kept.',
  waiting: 'Waiting to generate',
  interrupted: 'Interrupted',
  promptView: 'View prompt',
  promptViewImage: 'View the prompt for {image}',
  promptImageLabel: '{label} · Image {index}',
  promptImageText: 'Prompt for {image}',
  promptActual: 'Attempt {attempt} · Actual prompt',
  promptSaved: 'Saved prompt',
  promptPlanned: 'Original planned prompt',
  promptUnavailable: 'No prompt was saved for this image.',
  promptUnconfirmed: 'The generation version for this image was not saved; its actual prompt cannot be confirmed.',
  promptCopy: 'Copy prompt',
  promptCopyImage: 'Copy the prompt for {image}',
  promptCopying: 'Copying…',
  promptCopied: 'Copied',
  promptCopyFailed: 'Could not copy. Select the prompt above and copy it manually.',
  'status.queued': 'Queued',
  'status.running': 'Generating',
  'status.completed': 'Completed',
  'status.partial-failed': 'Partially failed',
  'status.failed': 'Failed',
  'status.cancelled': 'Cancelled',
  'status.interrupted': 'Interrupted',
} as const

export type EcommerceHistoryKey = keyof typeof en

const zh: Record<EcommerceHistoryKey, string> = {
  trigger: '历史任务',
  title: '电商历史任务',
  activeCount: '{count} 个进行中任务',
  search: '搜索商品名 / 提示词',
  statusFilter: '任务状态',
  modelFilter: '模型',
  sizeFilter: '比例',
  allStatuses: '全部状态',
  allModels: '全部模型',
  allSizes: '全部比例',
  autoSize: '自动',
  loading: '正在读取历史任务…',
  empty: '暂无电商任务。生成商品套图后，会在这里保存整套任务。',
  noMatches: '没有符合筛选条件的任务。',
  resetFilters: '重置筛选',
  retry: '重试',
  refresh: '刷新',
  close: '关闭历史任务',
  clear: '清空电商已结束任务…',
  clearHint: '保留进行中任务，仅清理电商任务。',
  open: '打开{name}',
  opening: '正在打开…',
  actions: '{name}的操作',
  remove: '删除任务…',
  cancel: '取消任务…',
  operationError: '操作失败：{message}',
  progress: '已完成 {done}/{total}',
  legacyProgress: '已保存 {count} 个结果',
  untitled: '未命名商品',
  legacy: '旧任务',
  legacyWarning: '此旧任务仅保存了结果，原配置和参考图无法完整恢复。',
  viewing: '正在查看已有任务',
  copyConfig: '复制配置为新任务',
  returnDraft: '返回草稿',
  modelUnavailable: '原模型或渠道当前不可用。复制配置后选择可用模型，再明确生成。',
  deleteConfirm: '删除「{name}」及其保存结果？此操作无法撤销。',
  clearConfirm: '将删除 {count} 个已结束的电商套图任务及其保存结果。{active} 个进行中任务会保留。普通生图记录、画布记录与图库收藏不受影响。',
  cancelConfirm: '取消「{name}」？已经生成的结果会保留。',
  waiting: '等待生成',
  interrupted: '已中断',
  promptView: '查看提示词',
  promptViewImage: '查看{image}的提示词',
  promptImageLabel: '{label} · 第 {index} 张',
  promptImageText: '{image}的提示词',
  promptActual: '第 {attempt} 次生成 · 实际提示词',
  promptSaved: '已保存提示词',
  promptPlanned: '原计划提示词',
  promptUnavailable: '此图没有保存可查看的提示词。',
  promptUnconfirmed: '未保存此图对应的生成版本，无法确认实际使用的提示词。',
  promptCopy: '复制提示词',
  promptCopyImage: '复制{image}的提示词',
  promptCopying: '正在复制…',
  promptCopied: '已复制',
  promptCopyFailed: '复制失败。可选中上方提示词，手动复制。',
  'status.queued': '排队中',
  'status.running': '生成中',
  'status.completed': '已完成',
  'status.partial-failed': '部分失败',
  'status.failed': '失败',
  'status.cancelled': '已取消',
  'status.interrupted': '已中断',
}

const ru: Record<EcommerceHistoryKey, string> = {
  trigger: 'История задач',
  title: 'История товарных задач',
  activeCount: 'Активных задач: {count}',
  search: 'Поиск по товару или запросу',
  statusFilter: 'Статус задачи',
  modelFilter: 'Модель',
  sizeFilter: 'Соотношение сторон',
  allStatuses: 'Все статусы',
  allModels: 'Все модели',
  allSizes: 'Все пропорции',
  autoSize: 'Авто',
  loading: 'Загрузка истории задач…',
  empty: 'Товарных задач пока нет. Создайте набор изображений, чтобы сохранить задачу здесь.',
  noMatches: 'Нет задач, соответствующих фильтрам.',
  resetFilters: 'Сбросить фильтры',
  retry: 'Повторить',
  refresh: 'Обновить',
  close: 'Закрыть историю задач',
  clear: 'Удалить завершённые товарные задачи…',
  clearHint: 'Активные задачи сохраняются. Удаляются только товарные задачи.',
  open: 'Открыть {name}',
  opening: 'Открытие…',
  actions: 'Действия для {name}',
  remove: 'Удалить задачу…',
  cancel: 'Отменить задачу…',
  operationError: 'Ошибка действия: {message}',
  progress: 'Готово: {done}/{total}',
  legacyProgress: 'Сохранённых результатов: {count}',
  untitled: 'Товар без названия',
  legacy: 'Старая задача',
  legacyWarning: 'В этой старой задаче сохранены только результаты. Исходные настройки и изображения нельзя восстановить.',
  viewing: 'Просмотр сохранённой задачи',
  copyConfig: 'Скопировать настройки в новую задачу',
  returnDraft: 'Вернуться к черновику',
  modelUnavailable: 'Сохранённая модель или провайдер недоступны. Скопируйте настройки и выберите доступную модель для новой генерации.',
  deleteConfirm: 'Удалить «{name}» и сохранённые результаты? Это действие нельзя отменить.',
  clearConfirm: 'Удалить {count} завершённых товарных задач и их результаты? Активных задач будет сохранено: {active}. Обычная история, записи холста и галерея останутся без изменений.',
  cancelConfirm: 'Отменить «{name}»? Готовые изображения сохранятся.',
  waiting: 'Ожидание генерации',
  interrupted: 'Прервано',
  promptView: 'Посмотреть запрос',
  promptViewImage: 'Посмотреть запрос для {image}',
  promptImageLabel: '{label} · Изображение {index}',
  promptImageText: 'Запрос для {image}',
  promptActual: 'Попытка {attempt} · Фактический запрос',
  promptSaved: 'Сохранённый запрос',
  promptPlanned: 'Исходный запланированный запрос',
  promptUnavailable: 'Для этого изображения запрос не сохранён.',
  promptUnconfirmed: 'Версия генерации этого изображения не сохранена; фактический запрос неизвестен.',
  promptCopy: 'Скопировать запрос',
  promptCopyImage: 'Скопировать запрос для {image}',
  promptCopying: 'Копирование…',
  promptCopied: 'Скопировано',
  promptCopyFailed: 'Не удалось скопировать. Выделите запрос выше и скопируйте вручную.',
  'status.queued': 'В очереди',
  'status.running': 'Генерация',
  'status.completed': 'Завершено',
  'status.partial-failed': 'Частичная ошибка',
  'status.failed': 'Ошибка',
  'status.cancelled': 'Отменено',
  'status.interrupted': 'Прервано',
}

/** Extra task-history copy follows the same live DSH locale as the studio. */
export function ecommerceHistoryCopy(key: EcommerceHistoryKey, values?: Record<string, string | number>): string {
  const language = activeImageGenLanguage()
  const table = language === 'zh' ? zh : language === 'ru' ? ru : en
  return table[key].replace(/\{(\w+)\}/g, (match, name: string) => values?.[name] === undefined ? match : String(values[name]))
}
